### ISSUE TITLE
Add support for chat

### ISSUE THREAD

**Issue by ghost** [achimala/leaguelib#11]
It would be awesome if this could interface with the LoL chat server, but what I think would be particularly useful is just being able to access the Summoner names of the people in a user's chat list as a "friends list", rather than having to make a user submit each summoner name individually for information.

**Comment by timlinde** [comment]
The LoL chat is like almost any other chat. Using the xmpp protocol and requires the summoners login credentials. And what do you mean by getting summonernames? 
You can send an array with summonerId's to getSummonerNames function and you get back an array with their names.

**Comment by ghost** [comment]
Sorry, maybe I am not yet familiar enough with the library. Is there a way to get the summonerId's for all users in chat list of the user's account?

**Comment by timlinde** [comment]
I am pretty sure you cant access the chat list without using the xmpp protocol. So you should look into that. If you like java, there is one guy who has made a copy of the league of legends client in java. And it has chat support (xmpp). That might give you some guidance on how to proceed. 
https://github.com/KolakCC/lol-jclient
Hope this was helpful.
