### ISSUE TITLE
Lack of real tutorial for setup

### ISSUE THREAD

**Issue by noxx2** [achimala/leaguelib#13]
EDIT: for anyone reading this, the MainTest.java file should really help you getting started.

I think this project is great work, so it deserves some kind of newbie-understandable tutorial. Me myself, as a JavaScript developer and webdesigner in general, I've been trying to put this up either as a standalone or a Play app, both without any success. Could you please provide something like that? Thanks

**Comment by tyxieblub** [comment]
The Main.java file in the test package should be enough, I think. What did you try and where did you fail ?

**Comment by noxx2** [comment]
Yeah, I'm sorry I only noticed that a few hours ago. I already got this up and running. The reason for this is probably that I haven't been coding in Java for a really long time, so I forgot a bit about the mechanics and stuff :D Once again sorry for this.
