### ISSUE TITLE
Match length question

### ISSUE THREAD

**Issue by martywachocki** [achimala/leaguelib#23]
I was wondering if anyone knows of a way to get either the end date for a match or the length of the match. I think lolking calculates it based on the IP earned although elophant.com and quickfind.kassad.in are seemingly able to get the exact game length.

Thanks!

**Comment by tyxieblub** [comment]
I've been trying to find out for a while now and couldn't figure how to do it. Well, if I remember correctly, you can find it easily for the ranked teams matches. Just use LoLNotes and see how the client get the details of a ranked team game. I guess there is a way to get the end game screen for other type of games too but I can't help you more than that, unfortunately.
