### ISSUE TITLE
Error running MainTest.java

### ISSUE THREAD

**Issue by sharklab** [achimala/leaguelib#33]
I encounter this issue everytime checking an active User (who is in game):

In login queue for EUW, #3 in line
Out here, waiting for it to finish
[nameOfChar]:
    accountID:  ****
    summonerID: ****
Getting profile data...
Getting leagues data...
Getting champ data...
Getting game data...
Profile:
    Prev Highest Tier: PLATINUM

League:
    Name: Viktor's Masterminds
    Tier: PLATINUM
    Rank: V
    Wins: 31
    ~Elo: 1887

Invoke:{result=_error, serviceCall=null, invokeId=12, data=flex.messaging.messages.ErrorMessage:{timestamp=1.390746086866E12, rootCause=com.riotgames.platform.messaging.UnexpectedServiceException:{message=null, localizedMessage=null, rootCauseClassname=com.riotgames.platform.messaging.UnexpectedServiceException, cause=null, substitutionArguments=[Ljava.lang.Object;@2d1e165f, errorCode=UNEXPECTED_ERROR}, headers=:{}, extendedData=null, body=null, faultDetail=null, correlationId=EA4E95D5-A267-829B-7679-B9F552D134E5, faultCode=Server.Processing, messageId=8C310CDD-B20F-2335-A837-4E6F482C2FF6, faultString=com.riotgames.platform.messaging.UnexpectedServiceException : null, timeToLive=0.0, clientId=8C310CBD-F51C-413B-A5EE-4749FBEBF170, destination=gameService}, version=0}
RTMP_ERROR

Has played Urgot
Has played Thresh
Has played Vayne
Has played Nidalee
Has played Kayle
Has played Master Yi
Has played Alistar
Has played Nasus
Has played Kennen
Has played Jinx
Has played Warwick
Has played Tristana
Has played Tryndamere
Has played Riven
Has played Leona
Has played Amumu
Has played Irelia
Has played Dr. Mundo
Has played Corki
Has played Janna
Has played Caitlyn
Has played Lulu
Has played Trundle
Has played Ziggs
Has played Blitzcrank
Has played Lissandra
Has played Wukong
No stats for <Champion Darius(#122)>
Client joined, terminating

Any ideas?

**Comment by hankditton** [comment]
Did you resolve this? Running into the same problem.
