### ISSUE TITLE
Send game invite

### ISSUE THREAD

**Issue by TheHolyWaffle** [achimala/leaguelib#34]
I've looked over the api but found nothing about this. Would it be possible to implement this?

**Comment by timlinde** [comment]
Leaguelib is a rtmp protocol based client.

The chat / game invites are based on xmpp/jabber protocol which is a complete different thing.

**Comment by TheHolyWaffle** [comment]
It does require to find the inviteId before it can be sent with xmpp. The only place where I thought I could find this was with this client.
