### ISSUE TITLE
Not getting all players from match history.

### ISSUE THREAD

**Issue by vincaslt** [achimala/leaguelib#4]
The getAllPlayers and getEnemyTeam and getPlayerTeam return only Id numbers for summoners, not the summoners themselves. Only the original player is returned as a complete LeagueSummoner object, all others have only one field filled in - index. Is it supposed to be so? What's the reasoning behind that?

**Comment by ghost** [comment]
From comments in PlayerStatsService

// IMPORTANT: Riot doesn't provide the summoner names of fellow players, only IDs
// This means that after calling fillMatchHistory, the match history of the summoner is populated
// but each match history entry's players only have valid IDs!
// You have to call SummonerService->getSummonerNames to batch resolve the IDs to names

**Comment by vincaslt** [comment]
Yes, that's what I figgured out, I thought you might have missed something when implementing, as I thought that you'd include that getSummonerNames call by default in the method. I didn't see that comment, so pardon me.
